name: Update Music List

on:
  push:
    branches:
      - main

jobs:
  updateMusic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch music from GitHub API
        run: |
          curl -H "Authorization: token ${{ secrets.CHRIBSTOKEN }}" \
          https://api.github.com/repos/chrisisediting/chribswebsite/contents/Music > music_list.json

      - name: Commit updated music list
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add music_list.json
          git commit -m "Update music list"
          git push
        env:
          GIT_AUTH_TOKEN: ${{ secrets.CHRIBSTOKEN }}

