name: Update Music List

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" 
jobs:
  updateMusic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch music from GitHub API
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/contents/Music > music_list.json

      - name: Commit updated music list
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add music_list.json
          git commit -m "Update music list"
          git push
